server:
  port: 8080
  servlet:
    context-path: /teach
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: anranzichi11
    url: jdbc:mysql://127.0.0.1:3306/tc_evaluation?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true